name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # Kích hoạt khi ông push code lên nhánh main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên máy ảo Linux của GitHub

    steps:
      - uses: actions/checkout@v4 # Lấy code từ repo về máy ảo

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        # Lệnh này chạy phase test và package để tạo file .jar
        run: mvn -B package

      - name: Upload Artifact
        # Lưu lại file .jar sau khi build xong
        uses: actions/upload-artifact@v4
        with:
          name: calculator-app
          path: Bai9_3/target/*.jar