name: Bai 6 Pipeline Optimization

on:
  push:
    paths:
      - 'Bai9_6/**' # Chỉ chạy khi ông sửa bài 6

jobs:
  optimize-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # ĐÂY LÀ PHẦN ĂN ĐIỂM BÀI 6:
          cache: 'maven'

      - name: Build and Test with Cache
        # Chạy lệnh package hoặc verify để Maven tải thư viện
        run: mvn -B package --file Bai9_6/pom.xml